name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend:
    name: Backend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore backend
        run: dotnet restore
        working-directory: ./backend

      - name: Build backend
        run: dotnet build --no-restore --configuration Release
        working-directory: ./backend

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/commerce-dashboard/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend/commerce-dashboard

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend/commerce-dashboard